# Generated by Django 4.0.4 on 2022-05-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.IntegerField()),
                ('invoice_date', models.CharField(max_length=10)),
                ('total', models.FloatField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('service_interval', models.IntegerField(default=12)),
                ('job_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsite.jobsite')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qb.invoice')),
            ],
        ),
    ]
