# Generated by Django 4.0.4 on 2022-05-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
    ]
