# Generated by Django 4.0.4 on 2022-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb', '0002_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.TextField(),
        ),
    ]
