# Generated by Django 4.0.3 on 2022-04-08 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_id', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_contact_name', models.CharField(max_length=100)),
                ('secondary_contact_name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('main_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('alternate_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('billing_address_1', models.CharField(max_length=200)),
                ('billing_address_2', models.CharField(max_length=200)),
                ('billing_address_3', models.CharField(max_length=200)),
                ('billing_address_4', models.CharField(max_length=200)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=2)),
                ('billing_zip', models.CharField(max_length=10)),
                ('jobsite_address_1', models.CharField(max_length=200)),
                ('jobsite_address_2', models.CharField(max_length=200)),
                ('jobsite_address_3', models.CharField(max_length=200)),
                ('jobsite_address_4', models.CharField(max_length=200)),
                ('jobsite_city', models.CharField(max_length=200)),
                ('jobsite_state', models.CharField(max_length=2)),
                ('jobsite_zip', models.CharField(max_length=10)),
                ('access_code', models.CharField(max_length=20)),
                ('next_service', models.DateField(null=True)),
                ('service_interval', models.IntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_supporting_technician', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('note', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customernotescategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEquipmentPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
                ('created_on', models.DateField()),
                ('customer_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerequipment')),
            ],
        ),
    ]
