# Generated by Django 4.0.4 on 2022-05-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='access_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='jobsite_address_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='jobsite_address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='jobsite_address_3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='jobsite_address_4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='jobsite_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='jobsite_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='jobsite_zip',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='next_service',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='primary_technician',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='requires_supporting_technician',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='service_interval',
        ),
    ]
