# Generated by Django 4.0.4 on 2022-05-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
