# Generated by Django 4.0.4 on 2022-05-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_billing_address_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='main_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
