# Generated by Django 4.0.4 on 2022-05-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
