# Generated by Django 4.0.4 on 2022-05-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_access_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_address_3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_address_4',
        ),
    ]
