# Generated by Django 4.0.3 on 2022-04-10 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0004_alter_customer_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
