# Generated by Django 4.0.3 on 2022-04-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_primary_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='primary_contact_name',
        ),
    ]
