# Generated by Django 4.0.4 on 2022-04-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='quickbooks_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
