# Generated by Django 4.0.4 on 2022-04-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_quickbooks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address_same_as_jobsite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
