# Generated by Django 4.0.4 on 2022-05-03 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_billing_address_same_as_jobsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.jobsite')),
            ],
        ),
    ]
