# Generated by Django 4.0.4 on 2022-05-03 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_jobsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSite',
        ),
    ]
