# Generated by Django 4.0.4 on 2022-05-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_delete_jobsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerequipmentphotos',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customerequipmentphotos',
            name='customer_equipment',
        ),
        migrations.RemoveField(
            model_name='customernotes',
            name='category',
        ),
        migrations.DeleteModel(
            name='CustomerEquipment',
        ),
        migrations.DeleteModel(
            name='CustomerEquipmentPhotos',
        ),
        migrations.DeleteModel(
            name='CustomerNotesCategory',
        ),
    ]
