# Generated by Django 4.0.4 on 2022-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
