# Generated by Django 4.0.4 on 2022-05-06 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_customerequipmentphotos_created_by_and_more'),
        ('equipment', '0005_alter_equipment_last_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.CreateModel(
            name='JobSiteEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_on', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
    ]
