# Generated by Django 4.0.5 on 2022-06-30 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX jobsite_index ON jobsite_jobsite (name, address, address_2, city, state, zip, '
             'phone_number, email)',),
            ('DROP INDEX jobsite_index on jobsite_jobsite',)
        ),
    ]
