# Generated by Django 4.0.4 on 2022-05-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsiteequipment',
            name='tags',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
