# Generated by Django 4.0.4 on 2022-05-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0002_alter_jobsite_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
