# Generated by Django 4.0.4 on 2022-05-09 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsite', '0002_jobsiteequipment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsiteequipment',
            name='added_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobsiteequipment',
            name='installed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
