# Generated by Django 4.0.3 on 2022-04-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('cost', models.FloatField()),
                ('default_image', models.URLField()),
                ('sales_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
