# Generated by Django 4.0.4 on 2022-05-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentvariation',
            name='default_image',
        ),
        migrations.RemoveField(
            model_name='equipmentvariation',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='equipmentvariation',
            name='url',
        ),
    ]
