# Generated by Django 4.0.4 on 2022-05-01 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_csr_phone_alter_supplier_sales_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0002_remove_equipment_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='default_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_updated_by',
            field=models.ForeignKey(default='auth.User', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
