# Generated by Django 4.0.4 on 2022-05-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipmentvariation_default_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentvariation',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
