# Generated by Django 4.0.4 on 2022-05-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_default_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
