# Generated by Django 4.0.4 on 2022-05-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_delete_equipmentvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
