# Generated by Django 4.0.4 on 2022-05-01 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_alter_equipment_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, default='auth.User', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
