# Generated by Django 4.0.4 on 2022-05-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='tags',
            field=models.CharField(max_length=512),
        ),
    ]
