# Generated by Django 4.0.4 on 2022-04-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='service_interval',
            field=models.IntegerField(),
        ),
    ]
