# Generated by Django 4.0.4 on 2022-04-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_billing_address_same_as_jobsite'),
        ('installation', '0002_alter_installation_service_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='service_interval',
            field=models.IntegerField(default=12),
        ),
    ]
