# Generated by Django 4.0.4 on 2022-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_alter_installation_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='requires_supporting_technician',
            field=models.BooleanField(default=False),
        ),
    ]
