# Generated by Django 4.0.4 on 2022-05-18 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=200)),
                ('contact_last_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('support_email', models.EmailField(max_length=254)),
                ('support_phone', models.CharField(max_length=15)),
                ('sales_email', models.EmailField(max_length=254)),
                ('sales_phone', models.CharField(max_length=15)),
                ('csr_email', models.EmailField(max_length=254)),
                ('csr_phone', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=150)),
                ('have_1099', models.BooleanField(default=False)),
                ('billing_address_1', models.CharField(max_length=200)),
                ('billing_address_2', models.CharField(max_length=200)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=2)),
                ('billing_zip', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('terms', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
