# Generated by Django 4.0.3 on 2022-04-08 21:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=200)),
                ('contact_last_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('support_email', models.EmailField(max_length=254)),
                ('support_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('sales_email', models.EmailField(max_length=254)),
                ('sales_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('csr_email', models.EmailField(max_length=254)),
                ('csr_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website', models.CharField(max_length=150)),
                ('have_1099', models.BooleanField(default=False)),
                ('billing_address_1', models.CharField(max_length=200)),
                ('billing_address_2', models.CharField(max_length=200)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=2)),
                ('billing_zip', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('terms', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
