# Generated by Django 4.0.4 on 2022-04-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='csr_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sales_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='support_phone',
            field=models.CharField(max_length=15),
        ),
    ]
